---
title: "vulnerable-places-charts"
output: html_document
---

```{r}

library(dplyr)
library(tidycensus)
library(tidyr)
library(ggplot2)
library(cori.charts)

library(sysfonts)
library(showtext)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/vulnerable-places-charts.Rmd")

```




```{r}

housing_stock_vulnerable <- readr::read_csv(here::here("data/housing_stock_by_city_subset_2018.csv")) %>%
  mutate(
    GEOID = stringr::str_pad(GEOID, 5, side = "left", pad = "0")
  )

housing_stock_metro <- readr::read_csv(here::here("data/housing_stock_by_city_metro_2018.csv")) %>%
  mutate(
    GEOID = stringr::str_pad(GEOID, 5, side = "left", pad = "0")
  )

cbsa_dta <- readr::read_csv(here::here("data/cbsa_eviction_proprietary_acs_2018.csv")) %>%
  mutate(
    GEOID = stringr::str_pad(cbsa10, 5, side = "left", pad = "0")
  )

```

```{r}

acs_vars <- c(
  "median_gross_rent" = "B25064_001",
  "median_hh_income" = "B19013_001",
  "housing_units_total" = "B25003_001",
  "housing_units_owner_occupied" = "B25003_002",
  "housing_units_renter_occupied" = "B25003_003",
  "median_hh_value" = "B25077_001",
  "hh_total" = "B25070_001",
  "hh_rent_burdened" = "B25070_008",
  "hh_rent_burdened" = "B25070_009",
  "hh_rent_burdened" = "B25070_010",
  "rent_burden" = "B25071_001"
)
  
acs_dta_13 <- get_acs("cbsa", variables = acs_vars, year = 2013)
acs_dta_18 <- get_acs("cbsa", variables = acs_vars, year = 2018)

acs_dta_clean_13 <- acs_dta_13 %>%
  select(GEOID, NAME, variable, estimate) %>%
  group_by(GEOID, NAME, variable) %>%
  summarise(
    estimate = sum(estimate, na.rm = T)
  ) %>%
  tidyr::pivot_wider(
    names_from = "variable",
    values_from = "estimate",
    names_glue = sprintf('{%s}_2013', "variable"),
  ) %>%
  mutate(
    pct_renter_occupied_2013 = housing_units_renter_occupied_2013 / housing_units_total_2013,
    pct_owner_occupied_2013 = housing_units_owner_occupied_2013 / housing_units_total_2013,
    pct_rent_burdened_2013 = hh_rent_burdened_2013 / hh_total_2013
  )

acs_dta_clean_18 <- acs_dta_18 %>%
  select(GEOID, NAME, variable, estimate) %>%
  group_by(GEOID, NAME, variable) %>%
  summarise(
    estimate = sum(estimate, na.rm = T)
  ) %>%
  tidyr::pivot_wider(
    names_from = "variable",
    values_from = "estimate",
    names_glue = sprintf('{%s}_2018', "variable"),
  ) %>%
  mutate(
    pct_renter_occupied_2018 = housing_units_renter_occupied_2018 / housing_units_total_2018,
    pct_owner_occupied_2018 = housing_units_owner_occupied_2018 / housing_units_total_2018,
    pct_rent_burdened_2018 = hh_rent_burdened_2018 / hh_total_2018
  )

pct_change_dta <- left_join(
    acs_dta_clean_13,
    acs_dta_clean_18,
    by = "GEOID"
  ) %>%
  mutate(
    pct_change_median_gross_rent = ifelse(
      median_gross_rent_2013 > 0,
      (median_gross_rent_2018 - median_gross_rent_2013) / median_gross_rent_2013, NA),
    pct_change_rent_burden = ifelse(
      rent_burden_2013 > 0,
      (rent_burden_2018 - rent_burden_2013) / rent_burden_2013, NA),
    pct_change_pct_rent_burdened = ifelse(
      pct_rent_burdened_2013 > 0,
      (pct_rent_burdened_2018 - pct_rent_burdened_2013) / pct_rent_burdened_2013, NA),
  ) %>%
  select(
    GEOID,
    pct_change_median_gross_rent,
    pct_change_rent_burden,
    pct_change_pct_rent_burdened
  )

```


```{r}

chrt_dta <- left_join(
    cbsa_dta,
    housing_stock_metro,
    by = "GEOID"
  ) %>%
  left_join(
    .,
    pct_change_dta,
    by = "GEOID"
  )

```


```{r}

# Scatter: Pct stock in 5 plus vs median gross rent increase

fig <- chrt_dta %>%
  ggplot(aes(x = pct_renter_occupied_5_plus_units, y = pct_change_median_gross_rent)) +
  geom_point(alpha = 0.5, color = "#211448", aes(size = total_renter_occupied_units)) +
  scale_x_continuous(
    labels = scales::percent_format(accuracy = 1, scale = 100),
    expand = expansion(mult = c(0.01, 0.01))
  ) +
  scale_y_continuous(
    labels = scales::percent_format(accuracy = 1, scale = 100),
    expand = expansion(mult = c(0.05, 0.05)),
  ) +
  scale_size_continuous(labels = scales::number_format(big.mark = ",")) +
  geom_smooth(color = "#E74F2A", method = "lm") +
  ggpubr::stat_cor(
    label.x.npc = 0.79,
    label.y.npc = 0.85
  ) +
  theme_cori() +
  theme(
    panel.grid.major.y = element_line(color = "#d0d2ce", linewidth =.1, linetype = "solid"),
    panel.grid.major.x = element_line(color = "#d0d2ce", linewidth =.1, linetype = "solid"),
    axis.line.x = element_blank(),
    plot.caption = element_text(family = "Lato", color = "dimgray", size = 8)
  ) +
  labs(
    title = "Metropolitan areas with more multifamily rentals had faster growing rents",
    subtitle = "Circles sized by number of renter occupied units, 2018",
    x = "Percent of rentals in multifamily buildings with 5 or more units",
    y = "Percent change in median gross rent (2013-2018)",
    caption = "Source: 2013 and 2018 ACS 5-year estimates. Gromis, Ashley, Ian Fellows, James R. Hendrickson, Lavar Edmonds, Lillian Leung, Adam Porton, and Matthew Desmond.\nEstimating Eviction Prevalence across the United States. Princeton University Eviction Lab.\nhttps://data-downloads.evictionlab.org/#estimating-eviction-prevalance-across-us/. Deposited May 13, 2022.\nNotes: CBSAs are Core-based statistical areas."
  )

save_plot(fig, here::here("export/pct_5_plus_units_vs_pct_change_rent.png"), add_logo = FALSE)


```


```{r}

# Rent increases in cities with widespread use of algorithmic rent pricing

focus_cbsa <- c(
  "42660", # Seattle
  "47900", # DC
  "19740", # Denver
  "34980", # Nashville
  "12060" # Atlanta
)

fig <- pct_change_dta %>%
  filter(GEOID %in% focus_cbsa) %>%
  mutate(
    name = case_match(
      GEOID,
      "42660" ~ "Seattle",
      "47900" ~ "Washington, D.C.",
      "19740" ~ "Denver",
      "34980" ~ "Nashville",
      "12060" ~ "Atlanta"
        )
  ) %>%
  ggplot2::ggplot(
    aes(
      pct_change_median_gross_rent,
      reorder(name, pct_change_median_gross_rent)
    )
  ) +
  ggplot2::geom_col(fill = "#49759C") +
  geom_text(
    aes(
      label = scales::percent(
        pct_change_median_gross_rent,
        accuracy = 1,
        scale = 100
      )
    ),
    fontface = "bold",
    hjust = -.2,
    family = "Lato"
  ) +
  ggplot2::scale_x_continuous(
    labels = NULL,
    expand = expansion(mult = c(0, .25))
  ) +
  theme_cori_horizontal_bars() +
  ggplot2::theme(
    panel.grid.major.x = element_blank()
  ) +
  ggplot2::labs(
    title = "Rents have increased more than 15% in metropolitan areas experiencing\nwidespread algorithmic rental pricing ",
    subtitle = "Percent change between 2013 and 2018 median gross rents",
    y = NULL,
    x = NULL,
    caption = "Source: American Community Survey 2013 and 2018 5-year estimates"
  )

save_plot(fig, here::here("export/rent_increases_in_major_algo_metro_areas.png"), add_logo = F, chart_height = 4)

```




